name: setup-r
description: Setup R
runs:
  using: composite
  steps:
  - uses: actions/cache/restore@v3
    id: cache-restore
    with:
      path: |
          /home/runner/.cmdstan
          /home/runner/work/_temp/Library
      key: r-setup-2|${{ hashFiles('renv.lock') }}|${{ hashFiles('ci/setup/*.R') }}

  - name: Install cmdstanr
    if: steps.cache-restore.outputs.cache-hit != 'true'
    run: Rscript ci/setup/install-cmdstan.R
    shell: bash

  - name: Install cmdstan and package
    if: steps.cache-restore.outputs.cache-hit != 'true'
    run: Rscript ci/setup/install-package.R
    shell: bash

  - uses: actions/cache/save@v3
    if: steps.cache-restore.outputs.cache-hit != 'true'
    id: cache-save
    with:
      path: |
          /home/runner/.cmdstan
          /home/runner/work/_temp/Library
      key: r-setup-2|${{ hashFiles('renv.lock') }}|${{ hashFiles('ci/setup/*.R') }}
