# Workflow derived from https://github.com/posit-dev/setup-air/tree/main/examples
on:
  pull_request:

name: air-format-suggest.yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
permissions: read-all

jobs:
  air-format-suggest:
    name: air-format-suggest
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Install
        uses: posit-dev/setup-air@v1

      - name: Format
        run: air format .

      - name: Suggest
        uses: reviewdog/action-suggester@v1
        with:
          level: error
          fail_level: error
          tool_name: air
