name: "Lint R Code With JARL"

on:
    push:
        branches: [prod]
    pull_request:
        branches: [prod]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: etiennebacher/setup-jarl@v0.1.0
              with:
                  args: check . --fix --output-format github
