# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [prod]
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

name: pkgdown

jobs:
  build:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
        extra-repositories:
          - "https://mc-stan.org/r-packages/"
          - "https://hubverse-org.r-universe.dev"

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "2.19.2"

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: true
          pak-version: rc
          extra-packages: any::pkgdown, local::.
          needs: website
          working-directory: wweval

      - name: Build site
        run: "pkgdown::build_site_github_pages('wweval', new_process = FALSE, install = FALSE)"
        shell: Rscript {0}

      - name: Upload artifact for GH pages deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: "wweval/docs/"

  post-artifact-to-pr:
    runs-on: ubuntu-latest

    if: ${{ github.event_name == 'pull_request' }}
    # This job depends on the `build` job
    needs: build

    # Required permissions
    permissions:
      contents: read
      pull-requests: write

    steps:
      # Post the artifact pulling the id from the `readme` step.
      # The msg will refer to the arfitact as 'README file'.
      - name: Post the artifact
        uses: CDCgov/cfa-actions/post-artifact@v1.2.1
        with:
          artifact-name: github-pages
          gh-token: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    if: ${{ github.event_name != 'pull_request' }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub pages
        uses: actions/deploy-pages@v4
