name: R CMD check project packages

on:
  pull_request:
  push:
    branches: [main, prod]

jobs:
  check-eval:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: "release"
        use-public-rspm: true
        extra-repositories: "https://mc-stan.org/r-packages/"
    - name: "Set up dependencies for wweval"
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        working-directory: wweval
        needs: check
    - name: "Install cmdstan via cmdstanr"
      uses: epinowcast/actions/install-cmdstan@v1
      with:
        cmdstan-version: "latest"
    - name: "Check wweval package"
      uses: r-lib/actions/check-r-package@v2
      with:
        working-directory: wweval

  check-ww:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: "release"
        use-public-rspm: true
        extra-repositories: 'https://mc-stan.org/r-packages/'
    - name: "Set up dependencies for cfaforecastrenewalww"
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        working-directory: cfaforecastrenewalww
        needs: check
    - name: "Install cmdstan via cmdstanr"
      uses: epinowcast/actions/install-cmdstan@v1
      with:
        cmdstan-version: "latest"
    - name: "check cfaforecastrenewalww package"
      uses: r-lib/actions/check-r-package@v2
      with:
        working-directory: cfaforecastrenewalww
        error-on: '"error"'
