name: Run Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.2'
    - run: sudo apt install -y pandoc git pandoc-citeproc make libssl-dev libfreetype6-dev libfribidi-dev libharfbuzz-dev libfontconfig1-dev libudunits2-dev zlib1g-dev libcurl4-openssl-dev libxml2-dev libgit2-dev libjpeg-dev libpng-dev libtiff-dev libicu-dev libglpk-dev libgmp3-dev libgdal-dev gdal-bin libgeos-dev libproj-dev libsqlite3-dev
    - uses: ./.github/actions/setup-r
    - run: Rscript ci/run/unit-tests.R
      shell: bash
#    - run: Rscript ci/run/test-vignette.R
#      shell: bash
